Continuing training at iteration -1
Top contributors:
Collecting rollouts (-1)...
Training network...
wandb: WARNING Step cannot be set when using syncing with tensorboard. Please log your step values as a metric such as 'global_step'
Top contributors:
	ML-bot: 1003451
Collecting rollouts (0)...
Training network...
Top contributors:
	ML-bot: 1003649
Collecting rollouts (1)...
Training network...
Top contributors:
	ML-bot: 1005479
Collecting rollouts (2)...
Training network...
Top contributors:
	ML-bot: 991450
Collecting rollouts (3)...
Training network...
Top contributors:
	ML-bot: 1010112
Collecting rollouts (4)...
Training network...
Top contributors:
	ML-bot: 1007422
Collecting rollouts (5)...
Training network...
Top contributors:
	ML-bot: 989442
Collecting rollouts (6)...
Traceback (most recent call last):
  File "c:/Users/manue/Downloads/Advanced ML Rocket League-bot project/learner.py", line 185, in <module>
    alg.run(iterations_per_save=10, save_dir="save")
  File "c:\Users\manue\Downloads\Advanced ML Rocket League-bot project\rocket_learn\ppo.py", line 165, in run
    self.calculate(_iter(), iteration)
  File "c:\Users\manue\Downloads\Advanced ML Rocket League-bot project\rocket_learn\ppo.py", line 254, in calculate
    for buffer in buffers:  # Do discounts for each ExperienceBuffer individually
  File "c:\Users\manue\Downloads\Advanced ML Rocket League-bot project\rocket_learn\ppo.py", line 157, in _iter
    rollout = next(rollout_gen)
  File "c:\Users\manue\Downloads\Advanced ML Rocket League-bot project\rocket_learn\rollout_generator\redis\redis_rollout_generator.py", line 161, in generate_rollouts
    data = self.redis.blpop(ROLLOUTS)[1]
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\commands\core.py", line 2473, in blpop
    return self.execute_command("BLPOP", *keys)
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\client.py", line 1242, in execute_command
    lambda error: self._disconnect_raise(conn, error),
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\client.py", line 1240, in <lambda>
    conn, command_name, *args, **options
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\client.py", line 1254, in parse_response
    response = connection.read_response()
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 249, in readline
    self._read_from_socket()
  File "C:\Users\manue\AppData\Local\Programs\Python\Python37\lib\site-packages\redis\connection.py", line 192, in _read_from_socket
    data = self._sock.recv(socket_read_size)
KeyboardInterrupt